#!/usr/bin/env sh
export EIDOCS_ROOT="${EIDOCS_ROOT:-/home/darrow/.local/share/eidocs}"
export EIDOCS_ENV_FILE="${EIDOCS_ENV_FILE:-/home/darrow/api-keys.env}"
export EIDOCS_OLLAMA_HOST="${EIDOCS_OLLAMA_HOST:-http://honjia:11434}"
export EIDOCS_OLLAMA_EMBED_MODEL="${EIDOCS_OLLAMA_EMBED_MODEL:-mxbai-embed-large:latest}"
export EIDOCS_EMBEDDING_DIM="${EIDOCS_EMBEDDING_DIM:-1024}"
export EIDOCS_RAG_INDEX="${EIDOCS_RAG_INDEX:-1}"
exec /dev-project/eibrain/.venv/bin/python -m eidocs.cli "$@"
